# --- !Ups

CREATE TABLE USER(
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  EMAIL VARCHAR(255),
  AVATAR_URL VARCHAR(255),
  ACTIVATED BIT
);

CREATE TABLE LOGIN_INFO (
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  PROVIDER_ID VARCHAR(255) NOT NULL,
  PROVIDER_KEY VARCHAR(255) NOT NULL
);

CREATE TABLE USER_LOGIN_INFO (
  USER_ID BIGINT NOT NULL,
  LOGIN_INFO_ID BIGINT NOT NULL
);

CREATE TABLE PASSWORD_INFO (
  HASHER VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  SALT VARCHAR(255),
  LOGIN_INFO_ID BIGINT NOT NULL
);

INSERT INTO USER(ID, FIRST_NAME, LAST_NAME, EMAIL, AVATAR_URL, ACTIVATED) VALUES
  (1, 'Test1', 'Test1', 'test1@test.com', NULL, TRUE),
  (2, 'Test2', 'Test2', 'test2@test.com', NULL, TRUE);

INSERT INTO LOGIN_INFO(ID, PROVIDER_ID, PROVIDER_KEY) VALUES
  (1, 'credentials', 'test1'),
  (2, 'credentials', 'test2');

INSERT INTO USER_LOGIN_INFO(USER_ID, LOGIN_INFO_ID) VALUES
  (1, 1),
  (2, 2);

INSERT INTO PASSWORD_INFO(HASHER, PASSWORD, SALT, LOGIN_INFO_ID) VALUES
  ('bcrypt-sha256', '$2a$10$RRA28oJNPvopDkCAWDXiSera5KLaCXPXiYVdq0qlFef8TVdGHXtvG', NULL, 1),
  ('bcrypt-sha256', '$2a$10$RUU3DucZBAMYIX3MyBXyLu4eQwJqWbEzYL05wzSnKcol0BIq2X9ZW', NULL, 2);

# --- !Downs

DROP TABLE PASSWORD_INFO;
DROP TABLE USER_LOGIN_INFO;
DROP TABLE LOGIN_INFO;
DROP TABLE USER;